export const SAVE_USER_TOKEN  = 'SAVE_USER_TOKEN';
export const CLEAR_USER_TOKEN = 'CLEAR_USER_TOKEN';

export const DIRECTORY_REQUEST_START       = 'DIRECTORY_REQUEST_START';
export const DIRECTORY_REQUEST_SUCCESSFULL = 'DIRECTORY_REQUEST_SUCCESSFULL';
export const DIRECTORY_REQUEST_FAIL        = 'DIRECTORY_REQUEST_FAIL';
